### ISSUE TITLE
MD Preview not working

### ISSUE THREAD

**Issue by StevenTCramer** [staruml/Markdown#3]
I am using StarUML 2.3.0 and the MarkDown extension is 0.9.3

When clicking the Preview button nothing changes.

**Comment by niklauslee** [comment]
Fixed in v0.9.4

**Comment by StevenTCramer** [comment]
Yes and working great ... THanks!

Steven T. Cramer
719.290.2872 (Mobile/Google)
419.757.0077 Office
2282 State Route 309
Ada, Ohio 45810
