### ISSUE TITLE
Table syntax doesn't work

### ISSUE THREAD

**Issue by tevosouza** [staruml/Markdown#4]
I'm trying to use the table syntax as follow

| Tables | Are | Cool |
| --- | --- | --- |
| col 3 is | right-aligned | $1600 |
| col 2 is | centered | $12 |
| zebra stripes | are neat | $1 |

but it isn't work, preview show me
`| Tables        | Are           | Cool  |
| ------------- |-------------| -----|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |`

**Comment by crzndx** [comment]
This in fact does still not work, why is this issue closed?
